name: fawnora
description: Submission for Project GTF.

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  cloud_firestore: ^2.4.0
  flutter_riverpod: ^0.14.0+3
  path_provider: ^2.0.2
  devicelocale: ^0.4.2
  google_fonts: ^2.1.0
#    permission_handler: ^6.0.1
  encrypt: ^5.0.0
#    flutter_spinkit: ^5.0.0
  device_info: ^2.0.2
  google_maps_flutter: ^2.0.6
#    geolocator: ^7.0.1
#    firebase_storage: ^8.0.2
#    auto_size_text: ^3.0.0-nullsafety.0
#    carousel_slider: ^4.0.0-nullsafety.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
#    xml: ^5.1.2
#    geocoding: ^2.0.0
# lint:^1.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  aes_crypt:
    git:
      url: git://github.com/cryoelite/aes_crypt.git
      ref: master

flutter:
  uses-material-design: true
  assets:
    - assets/splashImage.jpg
    - assets/keys/pKey.aes
    - assets/keys/aKey.aes
    - assets/keys/uKey.aes
    - assets/LoginProceedButton.png
    - assets/SignUpProceedButton.png
    - assets/StartButton.png
    - assets/StopButton.png
    - assets/TrackButtonActive.png
    - assets/TrackButtonInactive.png
    - assets/UploadButtonActive.png
    - assets/UploadButtonInactive.png
    - assets/LanguageButton.png
    - assets/BookSymbol.png
    - assets/Disturbance.png
    - assets/Disturbance_NFTP.png
    - assets/Disturbance_Sand_Mining.png
    - assets/Disturbance_Human.png
    - assets/Disturbance_Livestock.png
    - assets/Disturbance_Activity_Site.png
    - assets/Fauna.png
    - assets/Fauna_Birds.png
    - assets/Fauna_Mammal.png
    - assets/Fauna_Reptile.png
    - assets/Flora.png
    - assets/Flora_Grass.png
    - assets/Flora_Shrub.png
    - assets/Flora_Tree.png
    - assets/AssistiveAddButton.png
    - assets/KMLData/Aligarh.shp.kml
    - assets/KMLData/Allahabad.shp.kml
    - assets/KMLData/Badaun.shp.kml
    - assets/KMLData/Ballia.shp.kml
    - assets/KMLData/Bijnor.shp.kml
    - assets/KMLData/Bulandshahar.shp.kml
    - assets/KMLData/Chandauli.shp.kml
    - assets/KMLData/Etah.shp.kml
    - assets/KMLData/Farrukhabad.shp.kml
    - assets/KMLData/Fatehpur.shp.kml
    - assets/KMLData/Ghazipur.shp.kml
    - assets/KMLData/Hapur.shp.kml
    - assets/KMLData/Hardoi.shp.kml
    - assets/KMLData/Jyotiba_Phule_Nagar.shp.kml
    - assets/KMLData/Kannauj.shp.kml
    - assets/KMLData/Kanpur_Dehat.shp.kml
    - assets/KMLData/Kaushambi.shp.kml
    - assets/KMLData/Meerut.shp.kml
    - assets/KMLData/Mirzapur.shp.kml
    - assets/KMLData/Moradabad.shp.kml
    - assets/KMLData/Muzaffarnagar.shp.kml
    - assets/KMLData/Pratapgarh.shp.kml
    - assets/KMLData/Rae_Bareli.shp.kml
    - assets/KMLData/Sant_Ravi_Das_Nagar.shp.kml
    - assets/KMLData/Shahjahanpur.shp.kml
    - assets/KMLData/Unnao.shp.kml
    - assets/KMLData/Varanasi.kml

